version: '2'
services:
  nginx:
    image: daocloud.io/nginx:latest
    ports:
      - 53:53/udp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'io.daocloud.dce.compose.placement.constraints=["node.role==manager"]'
      - 'io.daocloud.dce.compose.mode=global'
